Productmaster
thanakijwanavit/villaMasterSchema pull request #7
Opened 2021-02-26 07:08 UTC by pathompongbo

add and update more fields.

2021-02-26 08:04 UTC, pinnareet requested changes

2021-02-26 08:04 UTC, pinnareet commented on productmaster/productmaster.yaml
> +    type: int
integer ไม่ใช่ int จ้า ฝากแก้ด้วยจ้า

2021-02-26 08:58 UTC, pinnareet commented on productmaster/productmaster.yaml
> +    type: string
prtype should be enum (I, C)

2021-02-26 09:07 UTC, pinnareet commented
more details here https://docs.google.com/spreadsheets/d/16NUZn-8vH8kW4bWyAUvPyn-0fYfWAve_2gNvXEk_AM4/edit?usp=sharing

2021-02-26 14:43 UTC, pinnareet commented
need to update more stuff but will pull for now per mickey's request

2021-03-01 03:51 UTC, thanakijwanavit commented
hello, are we ready for merge?

2021-03-03 11:35 UTC, pinnareet approved these changes

2021-03-03 11:36 UTC, merged